[workspace]
resolver = "2"

members = ["day-*"]
default-members = ["day-*"]

[workspace.dependencies]
tracing = "0.1.40"
custom_error = "1.9.2"
miette = { version = "5.10", features = ["fancy"] }
thiserror = "1.0.50"
tracing-subscriber = "0.3.18"